GET https://daljinac-test.herokuapp.com/routes

###

GET http://localhost:3000/actions

###

GET http://localhost:3000/actions/byDeviceId/612544


###
GET http://localhost:3000/actions/5e52ac73571e183becb82236


###
POST https://daljinac-test.herokuapp.com/actions
Content-Type: application/json

{
    "deviceID": "612544",
    "actionCode": "4444"
}

###

POST http://localhost:3000/actions
Content-Type: application/json

{
    "deviceID": "612544",
    "actionCode": "4444"
}

//USERS
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Pera",
    "password": "Peric",
    "email":"pera.peric@peric.com"
}