GET https://daljinac-test.herokuapp.com/routes

###

GET http://localhost:3000/routes/5e518580b2f17b3564aa1a5a


###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "deviceID": "5",
    "actionCode": "123123"
}